---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: tkeemon/rpi-os-ansible:v0.1.0
    command: pi1
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
